### ISSUE TITLE
Paper is 25 (25 frames) but code is 26 (26x512).

### ISSUE THREAD

**Issue by SnailTyan** [bgshih/crnn#81]
In paper:
For example, an image containing 10 characters is typically of size 100 × 32, from which a feature sequence **25** frames can be generated. 

In code:
model:add(cudnn.SpatialMaxPooling(2, 2, 1, 2, 1, 0)) -- 512x2x26
model:add(convRelu(7, true))                         -- 512x1x26
model:add(nn.View(512, -1):setNumInputDims(3))       -- 512x26
model:add(nn.Transpose({2, 3}))                      -- 26x512

**Why in paper it's 25 but in code it's 26 ?**

**Comment by kertansul** [comment]
Hi @bgshih, first of all, BIG thanks for the work on CRNN and sharing your code.

As today when I was scanning thru your paper/code, 
I noticed a minor difference about the unconventional pooling kernels:
< in paper >
    the suggestion is to adopt a 2x1 (matrix format) pool kernel
< in code >
    as shown above, it's implemented with normal 2x2 pool + stride 2x1

this is somehow related to what @SnailTyan is asking

TBH, since the code is working well, I guess it's just a minor adjustment
but curiosity drives me to search for an answer
Mind if you could share any thoughts about this?

**Comment by changwh** [comment]
@SnailTyan @kertansul Do either of you get the reason of this adjustment? I am also curious about it. If someone has any idea, please share your thoughts.:joy::joy::joy:

**Comment by changwh** [comment]
@kertansul @SnailTyan 
see:https://github.com/bgshih/crnn/issues/6
typo in paper
